"""
Django settings for apiv2 project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CURL_CERT_FILE = BASE_DIR + "/" + 'cacert.pem'

SSL_CACHE_DIR  = BASE_DIR + "/tmp/cache/ssl"

SSL_BIN_COMMAND ="/bin/bash " +  BASE_DIR + "/sslcert.sh {host} {port} {servername} {timeout}"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4=(jd=w$+=tvz415-4bkh3-=1s=we#l3-a77nz*wl%^ru#flbx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
DEBUG = True


ALLOWED_HOSTS = ['139.99.89.89', '0.0.0.0']

APPEND_SLASH = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pingpong',
    'corsheaders'
]

MIDDLEWARE = [
    'apiv2.classes.middleware.RequestStartedMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    
]

CORS_ORIGIN_WHITELIST = [
    "http://consoleapi.com",
    "https://consoleapi.com"

]



ALLOW_EXPOSE_CORS_DATA = {    
    'pingpong' : { 'test': {'METHODS':['GET'], 'EXPOSE_HEADERS': [ 'accept',   'accept-encoding',    'authorization',    'content-type',    'dnt',    'origin',    'user-agent',    'x-csrftoken',    'x-requested-with', 'X-CSApi-Authorization', 'X-CSApi-Referer', 'X-CSApi-Cookie', 'X-CSApi-Proxy', 'X-CSApi-SSL-Verifier', 'X-CSApi-Timeout', 'X-CSApi-Debug', 'X-CSApi-Pretty', 'X-CSApi-Http-Version', 'X-CSApi-IPv6', 'X-CSApi-Request-Url', 'X-CSApi-Follow-Redirection'], 'ALLOW_HEADERS': [ 'accept',   'accept-encoding',    'authorization',    'content-type',    'dnt',    'origin',    'user-agent',    'x-csrftoken',    'x-requested-with', 'X-CSApi-Authorization', 'X-CSApi-Referer', 'X-CSApi-Cookie', 'X-CSApi-Proxy', 'X-CSApi-SSL-Verifier', 'X-CSApi-Timeout', 'X-CSApi-Debug', 'X-CSApi-Pretty', 'X-CSApi-Http-Version', 'X-CSApi-IPv6', 'X-CSApi-Request-Url', 'X-CSApi-Follow-Redirection']}  }
}



CORS_ALLOW_HEADERS = ['*']
"""
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
"""



ROOT_URLCONF = 'apiv2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apiv2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'


from apiv2.configs.globalsettings import *


